defaults:
  - _self_

method: graph-mixup

train:
  total_epochs: 250
  validation_interval: 10

init:
  _target_: trainer.GraphMixup
  supervised_criterion:
    _target_: torch.nn.MSELoss
  optimizer: ${optimizer}
  scheduler: ${scheduler}
  unsupervised_weight: 1.0
  alpha: 1.0

    