defaults:
  - _self_

method: mean-teacher-trainer

train:
  total_epochs: 250
  validation_interval: 10

init:
  _target_: trainer.MeanTeacherTrainer
  supervised_criterion:
    _target_: torch.nn.MSELoss
  optimizer: ${optimizer}
  scheduler: ${scheduler}
  unsupervised_loss_weight: 0.05
  unsupervised_warmup_epochs: 20
  early_stopping:
    monitor: val_MSE
    patience: 20
    min_delta: 0.0
