defaults:
  - _self_

name: gat

init:
  _target_: models.GATv2
  _partial_: false
  num_node_features: 11
  hidden_channels: 128
  heads: 4
  local_layers: 3
  dropout: 0.0
  norm: batch
  res: true
  jk: null
