defaults:
  - _self_

name: gcn

init:
  _target_: models.GCN
  _partial_: false
  num_node_features: 11
  local_layers: 3
  hidden_channels: 128
  dropout: 0.0
  norm: batch # batch, layer or null
  res: true
  jk: lstm