defaults:
  - _self_

_target_: logger.WandBLogger
group: ${dataset.dataset_name} # Name of the group for wandb
name: ${model.name}_seed=${seed} # Name of the run for wandb
job_type: test
entity: andrezzb-deep-learning-gnn
project_name: deep-learning-gnn
disable: false
local_dir: ./logs #Directory to save logs
