defaults:
  - dataset: qm9
  - trainer: semi-supervised-ensemble  # options: self-supervised, supervised
  - optimizer: adamw
  - scheduler: cosine
  - logger: wandb
  - model: gcn #gin perfroms best
  - _self_


seed: 0 # Random seed
device: unset # Device to use (cuda or cpu) if unset will use cuda if available
force_deterministic: False # Force deterministic algorithms
debug_mode: False # Debug mode
result_dir: ./results
compile_model: false # Whether to compile the model with torch.compile

cps:
  enabled: true
  lambda_cps: 1.5 
