defaults:
  - dataset: qm9
  - trainer: cps  # options: self-supervised, supervised
  - optimizer: adamw
  - scheduler: cosine
  - logger: wandb
  - model: gcn #gin perfroms best
  - _self_


seed: 0 # Random seed
device: unset # Device to use (cuda or cpu) if unset will use cuda if available
force_deterministic: False # Force deterministic algorithms
debug_mode: false # Debug mode
result_dir: ./results
compile_model: false # Whether to compile the model with torch.compile
save_model: false # Whether to save the model after training
model_save_dir: saved_models/ # Directory to save the model

cps:
  enabled: true
  lambda_cps: 1.5
