defaults:
  - dataset: qm9
  - trainer: semi-supervised-ensemble
  - optimizer: adamw
  - scheduler: step
  - logger: wandb
  - model: gcn
  - _self_

seed: 0
device: unset
force_deterministic: false
model_path: null # Path to the model checkpoint (.pt file)
use_test: false  # If true, use the test dataloader instead of validation
